import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :asconvws, AsconvwsWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

prod_host = System.get_env("PROD_HOST") || "asconv.thelepton.com"

config :asconvws, AsconvwsWeb.Endpoint,
  url: [host: prod_host, port: 4001, scheme: "https"],
  check_origin: ["https://#{prod_host}"]
